# Generated by Django 5.2.3 on 2025-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Access type name', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Access Type',
                'verbose_name_plural': 'Access types',
                'db_table': 'access_type',
                'ordering': ['id'],
            },
        ),
    ]
